language: php

php:
 - 5.5
 - 5.6
 - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
 - curl -s https://getcomposer.org/installer | php
 - php composer.phar install --dev

script:
 - php vendor/bin/phpunit -c .

after_script:
 - php vendor/bin/coveralls -vvv

notifications:
  email: martin.aarhof@gmail.com
